### ISSUE TITLE
PrestaShop crashes while viewing orders in backend (isMyParcelCarrier called with null)

### ISSUE THREAD

**Issue by JanMiddelkoop** [myparcelnl/prestashop#11]
After installing version 1.0.1, when I go to the screen displaying all orders in the backend, PrestaShop crashes with a fatal error.

Type error: Argument 1 passed to Gett\MyparcelNL\Module\Hooks\Helpers\AbstractAdminOrder::isMyParcelCarrier() must be of the type int, null given, called in <snip>/modules/myparcelnl/src/Module/Hooks/OrdersGridHooks.php on line 142

I have temporarily fixed this error by removing the strict int requirement for the parameter to this function.

in: src/Module/Hooks/Helpers/AbstractAdminOrder.php
line: public function isMyParcelCarrier(int $idCarrier): bool
changed to: public function isMyParcelCarrier($idCarrier): bool

I can then view the orders screen properly at least.

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop: On our clean environment this works just fine. I will pass this along to our developers. Which version of prestashop are you using and could it be that you are using some plugins that might affect the order overview?

**Comment by JanMiddelkoop** [comment]
I think clean environment is your problem here.  I would presume this bug occurs when there are orders with a shipping method not via MyParcel, or with a MyParcel shipping method from the previous plugin.

We're using PrestaShop version 1.7.7.1; pretty sure this is not a compatibility issue with another module.

**Comment by rockincent** [comment]
Same problem over here. 
PS 1.7.7.2

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop @rockincent This issue will be fixed with the release of the next version. I will leave a message in this thread once it is available which I expect will be at the end of the week.

**Comment by okuryan** [comment]
@Mitchell-MyParcel , any news on release date?

**Comment by JanMiddelkoop** [comment]
@okuryan If you're running into this issue, check my first post/report here. The fix I posted is harmless and easily applied.  Just remove the word 'int' from the specific line in the code.

**Comment by okuryan** [comment]
@JanMiddelkoop , problem actually that this new reworked myparcel plugin breaks Prestashop admin panel in  1.7.7.2 totally (many places stopped to work ). For example product details page , order page. 

So as official Myparcel representative promised to release this week, I was hoping that it will fix also other issues. As now it is just crashing everywhere. 

I see that didn't happened yet and maybe we have to fix ourselves if that will not happen as promised by Myparcel.

**Comment by JanMiddelkoop** [comment]
@okuryan  What you're describing sounds like a different problem. Did you apply my fix and did that resolve the issue for you?

If it does, then great - you are running into the same problem.  You can apply the fix I posted for now and, assuming this issue will be resolved in the next release, just upgrade normally when it comes out.

If my fix does not resolve your problems, then you're facing a different issue. That means you should gather any errors from the logfiles, get as much debug data as possible (Prestashop version, modules installed, etc) and open a seperate issue here on GitHub. It doesn't help anyone to add data about different issues to this one.

**Comment by Mitchell-MyParcel** [comment]
@JanMiddelkoop @okuryan @rockincent @rockincent :  We have released a new version yesterday which should fix this problem. Could you check this?

You can download the new version here: https://github.com/myparcelnl/prestashop/releases/tag/v1.0.2

**Comment by ventor-dev** [comment]
@JanMiddelkoop , looks like Orders can be viewed on BACKEND. But Product page still not working.
See video https://drive.google.com/file/d/1rEvoA8W_IVXFED1BkK4nIhu1OYeV5Kc3/view

In /var/log/nginx/error.log I see below:
2021/03/31 08:30:46 [error] 106869#106869: *94 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 80PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 84PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 88PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 92PHP message: PHP Notice:  Undefined index: MYPARCELNL_RECIPIENT_ONLY in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 106PHP message: PHP Notice:  Undefined index: MYPARCELNL_AGE_CHECK in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 122PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 137PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 141PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 145PHP message: PHP Notice:  Undefined index: MYPARCELNL_RETURN_PACKAGE in /var/www/pre


Maybe doing smth wrong? Note that I cleared cache after module installation

**Comment by okuryan** [comment]
@Mitchell-MyParcel 

looks like Orders can be viewed on BACKEND. But Product page still not working.
See video https://drive.google.com/file/d/1rEvoA8W_IVXFED1BkK4nIhu1OYeV5Kc3/view

In /var/log/nginx/error.log I see below:
2021/03/31 08:30:46 [error] 106869#106869: *94 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 80PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 84PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 88PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_TYPE in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 92PHP message: PHP Notice:  Undefined index: MYPARCELNL_RECIPIENT_ONLY in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 106PHP message: PHP Notice:  Undefined index: MYPARCELNL_AGE_CHECK in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 122PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 137PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 141PHP message: PHP Notice:  Undefined index: MYPARCELNL_PACKAGE_FORMAT in /var/www/prestashop/var/cache/prod/smarty/compile/9b/3f/54/9b3f54f986c95454a5897f1c1c316577d4eb5a98_0.file.products_form.tpl.php on line 145PHP message: PHP Notice:  Undefined index: MYPARCELNL_RETURN_PACKAGE in /var/www/pre


Maybe doing smth wrong? Note that I cleared cache after module installation. 

PrestaShop version 1.7.7.2 + PHP 7.3

**Comment by JanMiddelkoop** [comment]
Hi @okuryan.  This is clearly a different issue than the one I reported.  On Github it is common practice to create your own issues for your own problems, unless someone is experiencing the same issue as you.

That helps developers to keep track of all the different issues, but it also helps you.  The original issue I reported is supposed to be fixed in the latest release; I will test this this afternoon.  If it is indeed fixed, this whole issue will be marked as fixed and closed, your comments here along with it.

So please, create a seperate issue for each problem you encounter, unless you are convinced you're experiencing the same issue as an already reported one.  When in doubt, always create a new issue.  The developers can mark it as identical if they discover it is.

**Comment by okuryan** [comment]
@JanMiddelkoop , @Mitchell-MyParcel I have created separate issue for this https://github.com/myparcelnl/prestashop/issues/18

But still this issue is a blocker to use the plugin

**Comment by JanMiddelkoop** [comment]
I can report this issue is resolved with the latest version of the plugin.

**Comment by Mitchell-MyParcel** [comment]
Since the original issue is solved I will close this thread. Our developer will look into the issue with the product page.
