### ISSUE TITLE
[BETA]: Gray screen after installation

### ISSUE THREAD

**Issue by mcrielaard** [myparcelnl/prestashop#235]
### Version check

- [X] My version of the plugin is v2.0.0-beta.0 or above.

### PrestaShop version

8.1.2

### PHP version

7.4.22

### What went wrong?

After installation i can't configure the MyParcel module totally empty grey screen. Try to reset module then the following error:

```
Kan actie Reset niet toepassen op myparcelnl. Error: Argument 2 passed to MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration::MyParcelNL\PrestaShop\Migration\Pdk\{closure}() must be of the type int, string given, called in /home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php on line 340

Stack trace:
#0 /.../modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php(340): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->MyParcelNL\PrestaShop\Migration\Pdk\{closure}()
#1 /.../modules/myparcelnl/src/Migration/Pdk/PdkProductSettingsMigration.php(97): MyParcelNL\Sdk\src\Support\Collection->each()
#2 /.../modules/myparcelnl/src/Migration/Pdk/PdkProductSettingsMigration.php(47): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->migrateProductSettings()
#3 /.../modules/myparcelnl/src/Migration/Migration2_0_0.php(30): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->up()
#4 /.../modules/myparcelnl/src/Migration/Migration2_0_0.php(14): MyParcelNL\PrestaShop\Migration\Migration2_0_0->runPdkMigrations()
#5 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(117): MyParcelNL\PrestaShop\Migration\Migration2_0_0->up()
#6 /.../modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php(340): MyParcelNL\Pdk\App\Installer\Service\InstallerService->MyParcelNL\Pdk\App\Installer\Service\{closure}()
#7 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(118): MyParcelNL\Sdk\src\Support\Collection->each()
#8 /.../modules/myparcelnl/src/Pdk/Installer/Service/PsInstallerService.php(136): MyParcelNL\Pdk\App\Installer\Service\InstallerService->migrateUp()
#9 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(49): MyParcelNL\PrestaShop\Pdk\Installer\Service\PsInstallerService->migrateUp()
#10 /.../modules/myparcelnl/src/Pdk/Installer/Service/PsInstallerService.php(57): MyParcelNL\Pdk\App\Installer\Service\InstallerService->install()
#11 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/Base/Facade.php(25): MyParcelNL\PrestaShop\Pdk\Installer\Service\PsInstallerService->install()
#12 /.../modules/myparcelnl/myparcelnl.php(101): MyParcelNL\Pdk\Base\Facade::__callStatic()
#13 /.../modules/myparcelnl/myparcelnl.php(162): MyParcelNL->{closure}()
#14 /.../modules/myparcelnl/myparcelnl.php(102): MyParcelNL->withErrorHandling()
#15 /.../src/Adapter/Module/Module.php(271): MyParcelNL->install()
#16 /.../src/Core/Module/ModuleManager.php(109): PrestaShop\PrestaShop\Adapter\Module\Module->onInstall()
#17 /.../src/Core/Module
```

### Reproduction steps

1. Install module
2. try to configure module
3. no configurations option available

### Relevant log output

```shell
Try to reset module then Error: Argument 2 passed to MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration::MyParcelNL\PrestaShop\Migration\Pdk\{closure}() must be of the type int, string given, called in /.../modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php on line 340

Stack trace:
#0 /.../modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php(340): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->MyParcelNL\PrestaShop\Migration\Pdk\{closure}()
#1 /.../modules/myparcelnl/src/Migration/Pdk/PdkProductSettingsMigration.php(97): MyParcelNL\Sdk\src\Support\Collection->each()
#2 /.../modules/myparcelnl/src/Migration/Pdk/PdkProductSettingsMigration.php(47): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->migrateProductSettings()
#3 /.../modules/myparcelnl/src/Migration/Migration2_0_0.php(30): MyParcelNL\PrestaShop\Migration\Pdk\PdkProductSettingsMigration->up()
#4 /.../modules/myparcelnl/src/Migration/Migration2_0_0.php(14): MyParcelNL\PrestaShop\Migration\Migration2_0_0->runPdkMigrations()
#5 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(117): MyParcelNL\PrestaShop\Migration\Migration2_0_0->up()
#6 /.../modules/myparcelnl/vendor/myparcelnl/sdk/src/Support/Collection.php(340): MyParcelNL\Pdk\App\Installer\Service\InstallerService->MyParcelNL\Pdk\App\Installer\Service\{closure}()
#7 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(118): MyParcelNL\Sdk\src\Support\Collection->each()
#8 /.../modules/myparcelnl/src/Pdk/Installer/Service/PsInstallerService.php(136): MyParcelNL\Pdk\App\Installer\Service\InstallerService->migrateUp()
#9 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/App/Installer/Service/InstallerService.php(49): MyParcelNL\PrestaShop\Pdk\Installer\Service\PsInstallerService->migrateUp()
#10 /.../modules/myparcelnl/src/Pdk/Installer/Service/PsInstallerService.php(57): MyParcelNL\Pdk\App\Installer\Service\InstallerService->install()
#11 /.../modules/myparcelnl/vendor/myparcelnl/pdk/src/Base/Facade.php(25): MyParcelNL\PrestaShop\Pdk\Installer\Service\PsInstallerService->install()
#12 /.../modules/myparcelnl/myparcelnl.php(101): MyParcelNL\Pdk\Base\Facade::__callStatic()
#13 /.../modules/myparcelnl/myparcelnl.php(162): MyParcelNL->{closure}()
#14 /.../modules/myparcelnl/myparcelnl.php(102): MyParcelNL->withErrorHandling()
#15 /.../src/Adapter/Module/Module.php(271): MyParcelNL->install()
#16 /.../src/Core/Module/ModuleManager.php(109): PrestaShop\PrestaShop\Adapter\Module\Module->onInstall()
#17 /.../src/Core/Module
```

### Additional context

![myparcel](https://github.com/myparcelnl/prestashop/assets/2943804/0c9bf5a4-32a9-4c11-bfc7-5020dd0173d5)

**Comment by mcrielaard** [comment]
Is there a workaround so i can install and configure this beta version in my test shop?

Martin

**Comment by EdieLemoine** [comment]
Hi @mcrielaard, do you see any errors in the console or network tabs of your browser's devtools when you're on the broken configuration page?

And it would be great if you could share the backend logs here, if there's any sort of error present. The files are in `<root>/var/logs/myparcelnl/*.log`. 

I've (probably) fixed the error you ran into during the reset/uninstallation flow, but can't tell what's causing the empty screen without more information.

**Comment by mcrielaard** [comment]
Hi, at the moment i'm not at the office. Can you supply me the fixes so i
can test it for you?

Best regards ,
Martin

Op wo 20 dec. 2023 11:55 schreef Edie Lemoine ***@***.***>:

**Comment by mcrielaard** [comment]
Okay now the module is asking for my API key. When i intered it the following error occured:
accountUpdateERROR handler ApiException: The class 'MyParcelNL\PrestaShop\Entity\MyparcelnlCarrierMapping' was not found in the chain configured namespaces PrestaShopBundle\Entity, MyParcelNL\PrestaShop\Entity\Concern, PrestaShop\Module\ProductComment\Entity
    at bm.doRequest (https://www.hetzilverhuys.com/new/modules/myparcelnl/views/js/backend/admin/dist/index.iife.js:21:65087)
    at async Object.Ce [as mutationFn] (https://www.hetzilverhuys.com/new/modules/myparcelnl/views/js/backend/admin/dist/index.iife.js:21:66593)

**Comment by EdieLemoine** [comment]
That's a common error we see a lot during development, but rarely hear about from users. This is usually resolved by clearing cache. For example, deleting the `<prestashop installation folder>/var/cache`, or going to `Advanced parameters -> Performance` and clearing the cache from there. Could you try this to see if it removes the error?

**Comment by mcrielaard** [comment]
Hi Edie, I removed the var folder but this doesn't resolve the error: ApiException: The class 'MyParcelNL\PrestaShop\Entity\MyparcelnlCarrierMapping' was not found in the chain configured namespaces PrestaShopBundle\Entity, MyParcelNL\PrestaShop\Entity\Concern, PrestaShop\Module\ProductComment\Entity.

**Comment by EdieLemoine** [comment]
@mcrielaard if this is still occurring, you can contact us at support@myparcel.nl to get better and faster support. They can help you via screen sharing and/or logging in to your website (if that's possible for you). 

This is a caching problem in PrestaShop itself though, and we can't do much about it. It also occurs with the existing module, so I'm closing this issue.

**Comment by mcrielaard** [comment]
Okay i will do that. In the mean time I have removed the myparcel configuration from the database. Then i have the oppertunity to fill in the API-key again. When i save the key an error is displayed which says the API-key is invalid. (but its the right one for sure). When i reload the module the module shows nothing. I don't think it is a cache problem because i cleared all the cache and removed the var folder.

**Comment by EdieLemoine** [comment]
If you're able to, please share relevant logs from `<root>/var/logs/myparcelnl/*.log`. Any exception in the backend (such as from requests) will be logged there. In this case it's probably in `error.log`

**Comment by mcrielaard** [comment]
Hi Edie,

Please find attached the myparcel zip.
[myparcelnl.zip](https://github.com/myparcelnl/prestashop/files/13839989/myparcelnl.zip)

**Comment by mcrielaard** [comment]
Please notice that my development shop is in a sub folder new.


```
{
"trace": [
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/MappingDriverChain.php",
"line": 89,
"function": "classNotFoundInNamespaces",
"class": "Doctrine\Persistence\Mapping\MappingException",
"type": "::"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php",
"line": 133,
"function": "loadMetadataForClass",
"class": "Doctrine\Persistence\Mapping\Driver\MappingDriverChain",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php",
"line": 343,
"function": "doLoadMetadata",
"class": "Doctrine\ORM\Mapping\ClassMetadataFactory",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php",
"line": 207,
"function": "loadMetadata",
"class": "Doctrine\Persistence\Mapping\AbstractClassMetadataFactory",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php",
"line": 313,
"function": "getMetadataFor",
"class": "Doctrine\Persistence\Mapping\AbstractClassMetadataFactory",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php",
"line": 40,
"function": "getClassMetadata",
"class": "Doctrine\ORM\EntityManager",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php",
"line": 816,
"function": "getRepository",
"class": "Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/var/cache/prod/Container2N1XNSl/EntityManager_9a5be93.php",
"line": 153,
"function": "getRepository",
"class": "Doctrine\ORM\EntityManager",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/src/Repository/AbstractPsObjectRepository.php",
"line": 35,
"function": "getRepository",
"class": "EntityManager_9a5be93",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 1934,
"function": "__construct",
"class": "MyParcelNL\PrestaShop\Repository\AbstractPsObjectRepository",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 52,
"function": "get270",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 1767,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 1777,
"function": "get241",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 52,
"function": "get239",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 655,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 52,
"function": "get58",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 1596,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 1601,
"function": "get210",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 52,
"function": "get209",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/.cache/CompiledContainer.php",
"line": 565,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 52,
"function": "get41",
"class": "CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Reference.php",
"line": 45,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php",
"line": 60,
"function": "resolve",
"class": "_MyParcelNL\DI\Definition\Reference",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php",
"line": 62,
"function": "resolve",
"class": "_MyParcelNL\DI\Definition\Resolver\ResolverDispatcher",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php",
"line": 111,
"function": "resolveParameters",
"class": "_MyParcelNL\DI\Definition\Resolver\ParameterResolver",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php",
"line": 62,
"function": "createInstance",
"class": "_MyParcelNL\DI\Definition\Resolver\ObjectCreator",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php",
"line": 63,
"function": "resolve",
"class": "_MyParcelNL\DI\Definition\Resolver\ObjectCreator",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Container.php",
"line": 321,
"function": "resolve",
"class": "_MyParcelNL\DI\Definition\Resolver\ResolverDispatcher",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/Container.php",
"line": 116,
"function": "resolveDefinition",
"class": "_MyParcelNL\DI\Container",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/php-di/php-di/src/CompiledContainer.php",
"line": 60,
"function": "get",
"class": "_MyParcelNL\DI\Container",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Base/Pdk.php",
"line": 60,
"function": "get",
"class": "_MyParcelNL\DI\CompiledContainer",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Base/Facade.php",
"line": 25,
"function": "get",
"class": "MyParcelNL\Pdk\Base\Pdk",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Context/Model/PluginSettingsViewContext.php",
"line": 40,
"function": "__callStatic",
"class": "MyParcelNL\Pdk\Base\Facade",
"type": "::"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Context/Service/ContextService.php",
"line": 77,
"function": "__construct",
"class": "MyParcelNL\Pdk\Context\Model\PluginSettingsViewContext",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Context/Service/ContextService.php",
"line": 131,
"function": "createPluginSettingsViewContext",
"class": "MyParcelNL\Pdk\Context\Service\ContextService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Context/Service/ContextService.php",
"line": 44,
"function": "resolveContext",
"class": "MyParcelNL\Pdk\Context\Service\ContextService",
"type": "->"
},
{
"function": "MyParcelNL\Pdk\Context\Service\{closure}",
"class": "MyParcelNL\Pdk\Context\Service\ContextService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Context/Service/ContextService.php",
"line": 46,
"function": "array_reduce"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Frontend/Service/FrontendRenderService.php",
"line": 214,
"function": "createContexts",
"class": "MyParcelNL\Pdk\Context\Service\ContextService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Frontend/Service/FrontendRenderService.php",
"line": 201,
"function": "renderTemplate",
"class": "MyParcelNL\Pdk\Frontend\Service\FrontendRenderService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Frontend/Service/FrontendRenderService.php",
"line": 148,
"function": "renderComponent",
"class": "MyParcelNL\Pdk\Frontend\Service\FrontendRenderService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/vendor/myparcelnl/pdk/src/Base/Facade.php",
"line": 25,
"function": "renderPluginSettings",
"class": "MyParcelNL\Pdk\Frontend\Service\FrontendRenderService",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/modules/myparcelnl/src/Controller/SettingsController.php",
"line": 18,
"function": "__callStatic",
"class": "MyParcelNL\Pdk\Base\Facade",
"type": "::"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
"line": 169,
"function": "index",
"class": "MyParcelNL\PrestaShop\Controller\SettingsController",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
"line": 81,
"function": "handleRaw",
"class": "Symfony\Component\HttpKernel\HttpKernel",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
"line": 201,
"function": "handle",
"class": "Symfony\Component\HttpKernel\HttpKernel",
"type": "->"
},
{
"file": "/home/zilverhuys/domains/hetzilverhuys.com/public_html/new/beheer/index.php",
"line": 84,
"function": "handle",
"class": "Symfony\Component\HttpKernel\Kernel",
"type": "->"
}
],
"template": "<div\n data-pdk-context="CONTEXT"\n id="ID"></div>\n<script id="ID-script">\n(() => {\n var e = 'EVENT_PONG';\n var listener = function(event) {\n event.detail.render('COMPONENT', '#ID');\n document.getElementById('ID-script').remove();\n document.removeEventListener(e, listener);\n };\n\n document.addEventListener(e, listener);\n document.dispatchEvent(new Event('EVENT_PING'));\n})();\n</script>\n",
"contexts": [
"pluginSettingsView"
],
"templateParameters": {
"ID": "pdk-plugin-settings-1266222642",
"COMPONENT": "PluginSettings",
"EVENT_PING": "myparcel_pdk_ping",
"EVENT_PONG": "myparcel_pdk_pong"
},
"contextArguments": []
}
```

**Comment by EdieLemoine** [comment]
Thanks for sharing the logs, it still shows no other error apart from the namespace thing, though, but the subfolder thing may be a good lead!

Please still contact IT support if you haven't yet, you'll still probably end up being helped by me, but it'll be easier to share more (secure) information and help quicker, in a more hands-on way than to comment back and forth. My coworkers will probably ask to share credentials for your site with us so we can get a closer look at the issues, for example. :)
